== 互联网协议

=== IP协议

头部（源IP地址 + 目的地IP地址）+ 数据 =< 64KB

IP提供的服务：不可靠或尽力而为。可能会丢失、重复、延迟或顺序错误，这些错误只在底层网络失败或目的地缓冲区满的时候才会发生。


IP唯一校验和：头部校验和。

不做数据校验和（端对端争论）：

- 避免经过路由时的开销。
- 交由应用层去校验数据和。

数据包大于底层网络MTU，发送端将IP数据包拆分（片段标识   符），在目的地重新组装。有时还会进一步分割数据包，以适应所经过的网络。

IP层必须在底层网络中插入消息目的地的"物理"网络地址（MAC），该地址可以从互联网网络接口层的地址解析获得。

地址解析模块：将互联网地址转为特定底层网络所使用的网络地址（有时称为物理地址）。

eg:如果底层网络是以太网，那么地址解析模块将把32bits的互联网地址转换为46bits的以太网地址。

转换与网络技术相关：

- 有一些主机直接与互联网数据包交换机相连，IP数据包可以不需要地址翻译就路由到它们。
- 一些局域网允许动态地将网络地址分配给主机，这样就可以方便地选择地址以匹配互联网地址中的主机标识符部分——翻译就是从IP地址中抽取主机标识符。
- 对于以太网和其他局域网，每个计算机的网络地址都是和他的网络硬件接口固定的，和互联网地址没有直接的关系——翻译取决于主机的IP地址和以太网地址间的对应关系，其具体实现是通过ARP（地址解析协议）完成的。

以太网中ARP：

为了能在计算机加入局域网时让IP数据包在以太网上传输，使用了动态询问并利用缓存来减少询问消息。

任务：发送方的IP软件模块在发送数据包前，必须将IP数据包中的接收方的互联网地址翻译成以太网地址。

每个主机上的ARP模块都维护一个缓存，保存它以前获得的（IP地址，以太网地址）对。

- 如果需要的IP在ARP模块缓存中，请求就会立刻被应答。
- 如果没有需要的IP，ARP会在本地以太网上发出一个以太网广播数据包（ARP请求数据包），数据包中包括了所需的IP地址。
- 本地以太网中每个计算机都会收到这个ARP包，用自己的IP地址与数据包的IP地址匹配。
1. 匹配：回应一个ARP包（包含自己的以太网地址）。
2. 不匹配：忽略此ARP包。
- 发送方的ARP根据响应维护本地的以太网地址映射表（IP地址，以太网地址），如果将来响应类似的ARP请求就不需要广播了。
- 通过上述方式，所有的计算机都有了最新的以太网映射表。
- 当新机子加入本地以太网的时候才需要ARP广播。


IP伪装

分布式拒绝攻击：使用ping，造成输入缓冲区溢出，正常的IP数据包将无法进入。

=== IP路由