== 互联网协议

IP:网际协议，互联网虚拟网络的底层"网络"协议。IP数据包为互联网和其他TCP/IP网络提供了基本的传输机制。
TCP：传输控制协议

TCP/IP规约没有详细描述互联网数据报层一下的层，互联网层的IP数据包会转换成可以在几乎任何底层网络或数据链路上传输的包。

TCP/IP独立于底层传输技术，这样使得互连网路可以有许多异构的网络或数据链路建立起来。隐藏了底层网络的多样性。



=== IP协议

头部（源IP地址 + 目的地IP地址）+ 数据 =< 64KB

IP提供的服务：不可靠或尽力而为。可能会丢失、重复、延迟或顺序错误，这些错误只在底层网络失败或目的地缓冲区满的时候才会发生。


IP唯一校验和：头部校验和。

不做数据校验和（端对端争论）：

- 避免经过路由时的开销。
- 交由应用层去校验数据和。

数据包大于底层网络MTU（二层MAC层的概念，以太网默认1500），发送端将IP数据包拆分（片段标识   符），在目的地重新组装。有时还会进一步分割数据包，以适应所经过的网络。

IP层必须在底层网络中插入消息目的地的"物理"网络地址（MAC），该地址可以从互联网网络接口层的地址解析获得。

地址解析模块：将互联网地址转为特定底层网络所使用的网络地址（有时称为物理地址）。

eg:如果底层网络是以太网，那么地址解析模块将把32bits的互联网地址转换为46bits的以太网地址。

转换与网络技术相关：

- 有一些主机直接与互联网数据包交换机相连，IP数据包可以不需要地址翻译就路由到它们。
- 一些局域网允许动态地将网络地址分配给主机，这样就可以方便地选择地址以匹配互联网地址中的主机标识符部分——翻译就是从IP地址中抽取主机标识符。
- 对于以太网和其他局域网，每个计算机的网络地址都是和他的网络硬件接口固定的，和互联网地址没有直接的关系——翻译取决于主机的IP地址和以太网地址间的对应关系，其具体实现是通过ARP（地址解析协议）完成的。

以太网中ARP：

为了能在计算机加入局域网时让IP数据包在以太网上传输，使用了动态询问并利用缓存来减少询问消息。

任务：发送方的IP软件模块在发送数据包前，必须将IP数据包中的接收方的互联网地址翻译成以太网地址。

每个主机上的ARP模块都维护一个缓存，保存它以前获得的（IP地址，以太网地址）对。

- 如果需要的IP在ARP模块缓存中，请求就会立刻被应答。
- 如果没有需要的IP，ARP会在本地以太网上发出一个以太网广播数据包（ARP请求数据包），数据包中包括了所需的IP地址。
- 本地以太网中每个计算机都会收到这个ARP包，用自己的IP地址与数据包的IP地址匹配。
1. 匹配：回应一个ARP包（包含自己的以太网地址）。
2. 不匹配：忽略此ARP包。
- 发送方的ARP根据响应维护本地的以太网地址映射表（IP地址，以太网地址），如果将来响应类似的ARP请求就不需要广播了。
- 通过上述方式，所有的计算机都有了最新的以太网映射表。
- 当新机子加入本地以太网的时候才需要ARP广播。


IP伪装

分布式拒绝攻击：使用ping，造成输入缓冲区溢出，正常的IP数据包将无法进入。

=== IP路由

互联网上的每个路由器都实现了IP层的路由，用以提供一个路由算法。

主干 ：

互联网的拓扑图在概念上被分割成自制系统（AS，Autonomous System），在被细分成区域。
每个AS都有一个主干区域。
将主干区域连接到主管区域的路由集合，以及将这些路由器互连的链路构成了网络的主干。
主干中的链路通常带宽很高，并且为保证可靠性，链路都被复制。

路由协议：

RIP-1是互联网上使用的第一个路由算法，是向量算法的一个版本。

[TIP]
支持RIP-1的路由器依然常见。新协议都具有向后兼容。可以与RIP-2，OSPF的路由器共存。

RIP-2由RIP-1发展而来，但包含了更多的功能，如无类别域间路由（CIDR）、更好的组播路由以及认证RIP数据包以避免路由器遭到攻击。

随着网络的发展，路由器处理要求的增大，早先的"向量算法"慢慢淘汰，因为收敛慢，且有潜在的不稳定性。现在趋于使用"链路——状态"算法。也成为开放最短路径优先（OSPF，Open shortest Path First）。比RIP算法收敛更快。

[TIP]
在IP路由器中可以渐进地采纳新路由算法。每个RIP数据包都会携带一个版本号。当引入一个新的RIP协议时，IP协议并不会改变。无论使用哪个协议，路由器都会找到一个路径（不一定是最优的）将IP包转发出去。

[WARNING]
对于在更新路由表过程中需要合作的路由,需要使用同一种路由协议.


默认路由:

随着互连网的规模增大,用路由表的方式去维护目的地,显然不可行.
两个解决方案:

1. 采用某种形式的IP地址拓扑分组
2. 如果离主干链路最近的关键路由器具有比较完整的路由表,那么大多数路由器的路由表信息的精确性可以放宽.
- 放宽的形式为路由表中具有默认的目的地项,此默认项指定了所有目的地址不在路由表中的IP数据包所使用的路由.
- 默认路由的使用在表格大小与路由有效性之间作出了折中.
- 互联网中没有一个路由器包含所有目的地的路由表

