= “第八章　用暗示带来的正向能量改变人生”

 

“No.1　我们之所以无法让潜意识实现健康、愉悦、善良和高效，就是因为我们不知道如何让潜意识接受这些信息。

No.2　所有的心理暗示都必须转化为自我暗示才能够发挥作用。我们要做的是：根据自己的需要主动选择适当的信息去进行心理暗示。

No.3　想象力是一个加工厂，人类所有的计划都是在这个工厂中铸就而成的。

No.4　榜样的暗示力量是无穷的。一个人、一个故事、一段话语，能点燃许多人心中的激情与梦想，让很多人的人生发生转变。

No.5　当生命之泉流经你的时候，你的思想是什么形状，生命就是什么形状。记住，今日的暗示，就是明日的你。”

 

“思想会对身体和精神造成影响，但这并不是说任何外来的思想都会在潜意识中变成现实。在心理学界普遍存在一种误区，也就是忽略了心理暗示起作用的真正原因。如果一个人牙疼，你对他说：“你不疼。”这句话一点用都没有，因为病人不但不接受这个信息，还会反对你的暗示，并对自己的疼痛感更加深信不疑。这句话加重了他对疼痛感的确认，于是，他更加疼了。”

 

“每一个进入显意识的思想，如果被潜意识接受，就会被潜意识转化为现实，并永远成为生活的一部分，这就是自我暗示的过程，我们的心理在这个法则的主宰下时时刻刻地运转。

我们之所以无法让潜意识现实健康、愉悦、善良和高效，就是因为我们不知道如何让潜意识接受这些信息。”

 

“潜意识接受或者拒绝某个思想，取决于这个思想会引起什么样的情绪。一个思想只有能激起与潜意识相容的情绪，才能被潜意识接受。反之，它就不会接受。如同酸碱中和一样，这个思想所携带的情绪会被之前的情绪抵消掉。”

 

“问：我使用了你所教授的方法，但是没有获得任何好转，为什么？

答：可能因为你思想深处的怀疑，你无意识地怀疑我的方法是否有效，也可能因为你意愿太强烈了，太想获得好转了。现在记住，太强的意愿来源于对病痛的恐惧。当意愿太强，那你就危险了，因为只要你太想去除病痛，就很容易受到病痛的暗示，所以获得病痛。”

 

“问：当事情让我烦躁时，我该怎么办？

答：当有事情烦你时，立刻重复“不，它根本没什么，不会让我烦躁，一点儿也不会，事情将会带来愉悦，而不是别的。”简而言之，这种想法将使我们进入良好的状态，而不是糟糕的状态。”

 

“前奏实验至少能严肃地证明三件事：第一，头脑中的一切想法都有转化成现实的倾向；第二，当自我暗示与意志发生冲突时，获胜的往往是自我暗示，在这种情况下，我们总会做出与我们的“意志”所希望的结果完全相反的事；第三，我们每个人都能轻而易举地不断想“我不能”或“我能”，所以，对我们来说，将我们希望得到的想法输入潜意识便是轻而易举的。”

 

“问：怎样才能实现我的愿望呢？

答：经常重复你的愿望，并说“我越来越相信”，你就能如愿以偿。如果你说“我的记忆力正在提高”“我越来越相信自己的记性越来越好”，那你的记性就会真的好起来。反之，那记性就会越来越差。你经常无意识地说出的话总是会实现，当然，不能违反常识。”

 

“心理暗示的过程分为两步：接受信息和把该信息转化为现实。这个过程是由潜意识来完成的。信息的来源并不重要，因为其过程是相同的：潜意识接受或拒绝信息——信息变成现实或作废。从本质上说，所有的心理暗示都必须转化为自我暗示才能够发挥作用。所以，我们要做的是，被动地去进行心理暗示，还是根据自己的需要主动选择适当的信息去进行心理暗示。”

 

“有一个不争的事实，即人们常常会“自我限定”，对自我和自我能力进行否定。这也是导致人们丧失天赋，无法成功的重要原因之一。有一些人，由于过去的失败就认为自己未来也无法获得成功，这就在潜意识中增加恐惧感。出于恐惧，人们不自觉地进行一次又一次消极的自我暗示，常常会“自我限定”，对自我和自我能力进行否定。”

 

“不敢去追求成功，是因为你的心里面默认了一个“高度”，这个高度常常暗示自己：成功是不可能的，是没有办法做到的。假设一下，如果上帝告诉你，你肯定能赚1000万元，那么你就不会给自己制定只赚100万元的目标。我们很多人就是因为不知道自己到底能实现多大的成功而低估了自己，从而影响了自己的前进。”

 

“你害怕表现失常，从而导致惨败，周围的人将会对你的能力产生怀疑，你的自尊和自信将受到严重打击，你会更加依赖于经验。你做事小心翼翼，害怕犯一丁点儿错，于是便在做每一件事之前自我设限。你的潜在能力终究没有爆发出来，只能像大多数人一样平庸地活着。”

 

“由于你早已习惯自我设限，就像给每个坟墓早已安上墓碑一样，破除这种恶习的一个重要方法是不断给自己制定新高度。这样，每个小目标都提高一点点，人生将会提高一个档次！”

 

“栽培正确的、纯正的思想并习惯性地向它供给始终指向相同目标的强大的积极思想，它就必定会不断找到克服一切障碍的方法和手段，最终发展成为一股强大的力量。”

 


“心理专家认为用言词来自我激励（暗示）很有效。
·我行，我能行！
·我喜欢我自己！
·我是最棒的！
·我一定会成功！
·今天美好的事情将会发生在我身上！”

 

“你要学会有意识地去重构你的思维方式和说话方式，你不想在生活中出现的事物，就要不要为它们提供任何生长的能量。只要有可能，避免一切消极的人影响到你的思想、情感和生活。”

 

“如果你对现状不满意，那你就设法改变它。如果改变不了，那就改变你的心态。”

 

“你关注什么，你的能量就会流向什么。恐怖只会带来更多的恐怖，暴力只会吸引暴力，抱怨只会带了更多消极的能量。”

 

“你头脑中的任何一条思想，你说的每一个字词，都是发出一条暗示信息。从这一刻开始，只关注你想要的东西，停止关注你不想要的事情，尽量避免使用任何限制或者消极的语言，学着用正面语言代替负面语言。停止抱怨那些让人失望的人，停止阅读那些给人带来不愉快的讯息，停止诉说那些糟糕透顶的气话，把心思花在你想要吸引的事物上面。”

 

“在日常行为当中，我们应该用一些黄金转换句，把消极思维转变成积极思维，并且把它们培养成为一种习惯。比如：
将“我不想迟到”改成“我会准时的”。
将“我不想忘记”改成“我会记住”。
将“我不能解决”改成“我会有办法的”。”

 

“想象力可以重塑你的思想，因为它可以使你的感觉发生新变化，从而形成新理想。就像锻炼你的肌肉一样，有效的训练可以让你拥有无限的想象力。”

 

“如果你的想法具有创造性与和谐性，那么你就将得到一个“好”的结果；如果你的想法充满了争斗或者不和谐，那么你得到的结果也必然是“坏”的。

“好”与“坏”只是为了表示我们行动的结果，或体现我们对这个法则的遵从与否。所以，你的精神态度才是解决人生问题的关键。”

 

“一件事情还没做，便去考虑失败后的结果，这样的心理暗示必然会在精神上增加不必要的负担，导致内在潜能得不到充分的调动与发挥，从而在困难面前束手无策。但若是你在脑海中反复想着成功，你就会发现真的能成功。”

 

“有时候，我们可以有意识地造成一种“自我成就感”，从而逐渐在心理上形成一种能抑制自卑情绪产生的良性循环机制。”

 

“你不相信吗？那就请回想一下过往的人生经历好了。想想那些日子，你因为担心某件事的发生而终日惴惴不安，可是最终，那件事还是发生了。你也许并未意识到，可是大脑中那担惊受怕的画面如此清晰，导致内在的潜意识深受影响，引来了错误的情形，让令你困扰的那件事情轻易地变成了现实。”

 

“你不妨放纵一下自己的想象，将自己的期待在脑海中进行清晰的预演。比如，想象着自己考入了理想的学府，想象自己掌控着一家大型的公司，想象自己在数万人的面前发表演讲……在心里告诉自己：“这就是未来的我，我一定要去实现！”有了这样的心理预期，从前的干扰已经不再对你起作用，你能够自由地发挥自己真正的潜力。”

 

“所谓榜样暗示就是利用在某一领域的佼佼者作榜样，暗示自我学习、模仿其成功的地方。榜样的暗示力量是无穷的。一个人、一个故事、一段话语，看似平凡简单，却能点燃许多人心中的激情与梦想，让很多人的人生发生转变。”

 

“他之所以能挺过去，就是靠着一个信念：“我一定能成为一个出色的推销员。”
每天早上出门之前，他都要对着镜子里的自己说：“卡腾堡，如果你要吃饭，就得做这件事。既然非做不可。那你何必不做得痛快一点儿呢？就假想你是一个演员，正站在舞台上，下面有很多观众正注视着你。你现在做的事就像演戏一样，何必不高兴点儿呢？”

 

“每天早晨给自己打气，是不是一件很傻、很肤浅、很孩子气的事呢？不是的，这在心理学上是非常重要的。我们知道，一个人在熟睡之前或尚未完全清醒之前，潜意识是最活跃的时间，在潜意识活跃的状态下，暗示具有较好的效果。”

 

“你从事创造性的工作，你可以这样暗示自己：“我头脑聪明，富有创造性。我能力很强，才华出众。一定能设计出高水平的新产品来。”如果你希望自己心情愉快，可以对自己微笑着说：“我现在的心情很好，笑容很灿烂，情绪也很稳定，精神很旺盛。”反复在心中默念，你的心情必定会转好。如果你想改掉拖拉的坏习惯，你可以对自己说：“我的时间很宝贵，我惜时如金。”

总之，你期望自己成为什么样的人，想要什么样的生活，你就在清晨怎样暗示自己。记住，今日的暗示，就是明日的你。”

 

