= “第二卷：群体的意见与信念   第一章　群体信念和意见的间接因素”

 

“这里我们就只以其中最具震撼力的法国大革命为例，它的间接因素中包含了哲学家们的著作、贵族阶级的剥削、科学思想的进步。有了这些准备，群体的心灵很容易就能被那些直接因素所激发，比如演说家的演讲，比如朝廷拒绝接受任何微小的改良。

在间接因素当中，有一些普遍性因素，是所有群体信念和意见的基础。这些因素是：种族、传统、时间、制度、教育。”

 

“没有传统，就没有文明；没有对传统的缓慢淘汰，就没有进步。困难在于，如何在稳定和变动之间找到一个恰当的平衡；而这个困难是巨大的。当一个民族经过一代代的传承，已经让自己的习俗固定得过于牢固，它就很难再进行改变，就像中国那样，没有改进的能力。暴力革命对此也没有用处，因为它所带来的结果，要么是打碎的锁链重新拼接起来，过去的模式原封不动地重现，要么是任凭社会支离破碎，旧时代的衰落很快地被无政府状态所替代。

因此，对于一个民族而言，理想的状态是保持过去的制度，以难以察觉的方式一点一点地改变它。这种理想是很难实现的。古代的罗马人，近代的英国人，差不多是唯一把它变为现实的两个民族。”



“顽固坚守传统观念、执拗反对变革的，正是群体，尤其是拥有社会地位的那一类群体。”

 

“时间才是我们名副其实的主人，只需听凭它的支配，就可以看到所有的事物是如何变化的。如今，我们面对群体危险的渴望以及其所预示的破坏和骚乱深感不安。唯有等待时间来重建平衡。拉维斯先生所言极是：“没有哪个政权，可以在一天中建成。政治和社会组织是需要历经数百年建设的事业；封建制度在形成自己的章法之前，经历了好几个世纪的混乱与摸索；绝对君权也是经历了数百年之后，才找到了统治的成规，而且在等待成型的阶段，同样也充满了动荡。”

 

“一个民族根本没有力量去真正改变自己的制度。的确，他们能够以暴力革命为代价，改变制度的名称，但其实质并没有改变。名称只不过是一些无用的标签，深入事物本质的历史学家们根本不会对它们加以留意。所以说，英国虽然在君主制度的统治之下，却是世界上最民主的国家[24]，而那些原属西班牙的美洲共和国，尽管有着共和制的宪法，其实却处在最严酷的专制统治之下。决定各民族命运的，不是它们的政府，而是它们的性格。”



“把时间浪费在炮制各种宪法条例上，只不过是幼稚的把式，是无用且愚蠢的修辞练习。真正负责制定宪政的，是必要性以及时间，而我们则应明智地让这两个因素发挥作用。”



“丝毫不要考虑严谨对称，更多地是考虑方便实用；绝不单纯地因为不一致而去消除不一致；若非感觉到不满，就绝不改革；若要改革，就要彻底解决不满；只针对具体问题对症下药，绝不制定任何范围更大的条款——就是这些原则，从约翰国王时代到维多利亚女王时代，一直指导着我们二百五十年的议会作出决策。”



“我们应该对每个民族的法律和制度进行逐一检视，才能展现它们是在多大程度上体现了其种族的需求，以及是否因此而不需被粗暴地改革。我们可以从哲学角度论述诸如集权制的利与弊这样的问题，然而，当我们看到，一个由不同种族构成的国家，它的国民花了一千年的努力来推进集权制；当我们发现，一场以打破所有旧制度为目标的大革命，不仅不得不尊重这种集权制，甚至还将其强化，我们就该承认它是绝对需求的产物，是生存本身的条件。对于那些奢谈毁掉这种制度的政客，我们唯有怜悯他们浅薄的见识。如果他们碰巧做成了这件事，那么，成功的时刻也正预示着一触激发的可怕内战，内战又立即会带来比旧政权更具压迫性的新的集权制度。”



“从以上所述中我们可以得出结论，即不能从制度中去寻找能够深刻影响群体禀性的手段；我们看到一些国家，比如美国，通过民主制度取得了高度的繁荣，但我们也看到其他一些国家，比如那些共和制下的西班牙语美洲国家，尽管有着几乎完全相似的制度，却生活在极其可悲的混乱当中。因此我们可以说，这个国家的伟大，或那个国家的堕落，与制度本身都是不相干的。各民族受自身性格的支配，一切与其性格不相称的制度，都只不过是一件借来的外衣，一种暂时的伪装。”



“民主观念与心理学和经验所提供的数据有着深刻的差异。包括赫伯特·斯宾塞在内的许多杰出心理学家，都已经毫不费力地证明，教育既不能令人变得更有道德，也不能使人更幸福，它无法改变人的本能和世代相传的冲动；而且有时候——很容易就会受到不良引导——带来的坏处远远大于好处。统计学家已经证实了这些观点，他们说，犯罪现象是随着教育的普及，或者说至少是某种教育的普及而增长的；社会最坏的敌人，无政府主义者，通常都曾是学校里名列前茅的人；而且，在最近的一项研究中，杰出的法官阿道夫·吉约先生指出，目前，受过教育的罪犯和文盲罪犯的比例是3000∶1000，并且，在五十年的时间里，犯罪人数从四十万居民中的二百二十七人上升到五百五十二人，即增长了133%。他和他的同行们还注意到，犯罪率主要是在年轻人中增长，而众所周知的是，正是为了年轻人，法国用免费义务教育代替了收费教育。”


“没有人会坚持说，即便正确引导的教育也无法得出有益的成果。就算它不能提升道德品质，但起码可以发展职业技能。不幸的是，拉丁民族，尤其在近二十年来，将他们的教育体制建立在十分糟糕的原则之上，并且，尽管有那些最优秀的头脑对此提出意见，他们仍然坚持走在错误的道路上。我本人也在另一本著作中[27]指出，我们当前的教育把大多数接受这种教育的人变成了社会的敌人，为最糟糕的社会主义阵营招募了大量门徒。

这种教育（非常符合拉丁民族的特性）的首要危险在于，它建立在错误的基本观念上，认为智力的发展是通过对教科书的死记硬背。因此，人们致力于尽可能多地去记忆课本；从小学到博士，甚至到教师资格会考，年轻人都只知道背书，他们的判断力和主动性从来没有得到锻炼。教育对他而言，是背诵和服从。“学习课程，熟记一条语法或者一段摘要，不断重复，顺利模仿，如此而已。前公共教育部长朱勒·西蒙先生这样写道，“这实在是一种可笑的教育，所有的努力都是一种信仰行为，默认教师不会犯错误，这样的教育导致的结果只会让我们贬低自己，变得无能”。”

 

“这样的教育带来的危险远比这些严重得多。它让接受这种教育的人强烈地厌恶自己的出身，并迫切渴望脱离这样的环境。工人不想再当工人，农民不想再当农民，资产阶级中的落魄者，不希望自己的儿子从事除了国家公务员以外的任何职业。学校不是在帮助人们为生活做准备，而是仅仅为了从事公共服务做准备，在这个领域里要想取得成功，完全不需要自我定向，也无需展现出任何积极主动性。这种制度在社会底层造就了一支无产阶级的大军，他们对自己的命运愤愤不平，时刻准备着造反；而在社会的高处，则培养了一批轻浮肤浅的资产阶级，他们既多疑又轻信，对他们亲爱的国家抱着迷信一般的信任，却又时不时对其加以责难，总是把自己的过错归咎于政府，但倘若没有当局的介入，他们又什么事都干不了。”



“在生活中，判断力、经验、进取心和个性，这些才是取得成功的条件，这些都不是书本所能够给予的。”

 

“怎样用专业教育提高智力，彻底地超越传统教育呢？泰纳先生对此作出了出色的解释：
观念只有在自然而正常的环境中才能形成；观念的萌芽生长，来自于年轻人每一天所接收到的大量感官印象，他们需要出入工厂、矿山、法庭、事务所、建筑工地、医院，见识各种工具、材料和操作，与顾客、工人们相处，参与劳作，无论干得是好是坏，或赚或赔：这些就是眼睛、耳朵、双手，甚至嗅觉所获得的独特认知，这些细微的感知在不经意间潜移默化，在年轻人的心中逐步成型，或迟或早地促使他们产生新的做事方式，或简化、或节省、或改进、或创造。所有这些宝贵的接触，所有诸如此类必不可少的学习元素，都在法国年轻人最有生产力的年华里被剥夺了；在七八年的时间里，他们被关在学校，远离亲身体验的机会，因此无法对事物、对人、对不同的处理方式形成鲜明而准确的概念。”

 ”

“……十人中至少有九人浪费掉了他们的时间和精力，他们人生中好几年的光阴。这些年正是最有效、最重要，甚至具有决定意义的几年：先算算一半到三分之二参加考试的人——我指的是那些失利者；然后，再看看那些被录取、获得学位、取得证书、拿到文凭的人当中，还有一半到三分之二这样的人——我指的是那些劳累过度的人。他们被要求在某一天，坐在一把椅子上，或在一块黑板前，连续两个小时面对答辩团，展示自己所记诵的所有人类知识条目；事实上，只有在那一天的那两个小时里，他们能够背得出来；而一个月以后，他们就无能为力了；他们无法再经受考试；他们所学习的内容太多太繁重，不停地从他们的头脑中溜走，却没有新的补充进来。他们的精神活力衰退了；他们生长的能量干涸了；一个人长成了，但往往也结束了。这个人，成家、立业，陷入生活的循环，在周而复始的循环中，封闭在狭小的办公室里；他兢兢业业地完成自己的那份工作，除此之外再无其他。这就是平庸的回报；显然，收益和消耗不成比例。在1789年以前，法国就和英国、美国一样，采用的是相反的过程，但所得到的回报相当，甚至更多。”



“在教育的三个阶段，即童年、少年和青年期，为了考试、学位、文凭、证书而坐在板凳上啃书本背理论，这样的准备期被拖延得太长了，负荷也过重了。就为了这些目的，我们用的是最糟糕的方式，执行的是违反自然天性、违反社会规律的教育体制，对见习实践冷眼相看，推行寄宿制度，进行纸上谈兵的训练和填鸭式教学，超负荷施压，不考虑往后的日子，不考虑成人的年龄和他们将要承担的工作，也不考虑年轻人将要面临的是怎样一个现实的世界，不考虑他们要为周遭的社会作出怎样的适应或妥协，不考虑人为了生存和立足所进行的斗争，他们必须准备充足、装备齐全、训练有素、百折不挠。这是必不可少的装备，这样的习得比其他任何知识习得都更重要，这种牢靠的常识、意志和干劲，我们的学校教育都没有提供，甚至恰恰相反，它们不但没有赋予年轻人这样的能力，反而破坏了他们面对未来应有的素质。当他步入社会，他在职场上迈出的第一步往往都是一连串痛苦的失败；他撞得鼻青脸肿，创伤久久不愈，有时甚至落得终身残缺。这样的体验粗暴且危险；道德和心理的平衡被破坏，恐怕再难以恢复；幻灭产生了，格外粗暴，格外彻底；失望如此之大，挫败感如此强烈。”

 

“我们以上所述是否偏离了群体心理学的主题？我想并非如此。倘若我们想了解今天正在酝酿、明日将会诞生的思想与信念，就必须知道它们的土壤是如何形成的。一个国家为其年轻人所提供的教育，可以让我们看到这个国家未来的样子。在改善或恶化群体心智上，教育都在其中发挥了一部分的作用。因此，有必要呈现当前的制度是如何塑造了群体心智，冷漠而中立的大众是怎样一步步成为心怀不满的庞大队伍，随时准备听命于乌托邦分子与演说家们的教唆。今天，正是在学校里，愤世嫉俗者与无政府主义分子们被培养出来，正是在学校里，拉丁民族走向衰败的道路被铺就。”

 

