= “第二章　群体的情感与道德”




“1.群体的冲动、易变和急躁”



“群体受到一切外部刺激因素的摆布，并由此反应出不断的变化。因此，群体是各种冲动的奴隶。孤立的个体也会像群体中的个体那样受到同样的刺激，但由于大脑会告诉他冲动的危害，所以他不会任由其摆布。用心理学语言来表述的话，我们可以说：孤立的个体具有控制自身反应行为的能力，而群体则不具备。”



“激群体的因素千差万别，但群体始终对它们唯命是从，其结果就是：群体是极度多变的；也正是因此，我们看到群体会在转瞬之间从最血腥的残暴转变为最纯粹的宽容或英勇。”



“群体不只是冲动和易变。他们不承认横亘在欲望与实现欲望之间的任何障碍，因为他们的数量之众，令他们觉得自己拥有无可抵挡的力量。对于一个群体中的个人而言，不可能的概念消失了。孤立的个人很清楚自己不会单枪匹马地去火烧宫殿、抢劫商店，而且即便他想这样做，他也会很容易抵制住这种诱惑。而当他成为群体中的一员时，他会意识到人数所赋予他的力量，只要激发他烧杀劫掠的念头，他立刻就会屈从于这样的诱惑。意料之外的障碍都会被疯狂所粉碎。如果狂热是人类机体的一种固有属性，那么我们可以说，欲望受阻的群体所表现出的正常状态，就是狂热。”




“2.群体的易受暗示和轻信”




“假如群体是中立的，那么它往往处在一种观望状态中，所以它非常容易受到暗示。第一个突然形成的暗示，会立刻通过传染作用占据所有人的大脑，而情感倾向也旋即建立。在所有受到暗示的人群中，占领了他们头脑的那个念头，将会转变为行动。不管是放火烧宫殿的行动，还是自我牺牲的行动，群体都在所不辞。一切都取决于刺激因素的性质，而不再像孤立的个人那样，取决于受暗示的行为和所有理由之间的关系，后者可能与这一行为的实现是对立的。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books.

“群体总是游荡在无意识的边缘，极易接受任何的暗示，表现出不受理性左右的生物所特有的强烈情感，完全不具备批判能力，除了极度轻信，其他什么也不会。对群体而言，没有什么是不可能的，记住这一点，就能理解为什么那些最荒谬的传说和故事会那么容易地被编造和传播开来。”



“群体是靠形象思考的，而一个被唤起的形象，又会唤起一系列与它毫无逻辑联系的其他形象。这种状态并不难理解，只要想想，我们自己有时也会被随便什么事引发一连串奇怪的幻想。理性告诉我们，那些形象之间并没有任何关系，但群体对此却视若无睹；他们把歪曲的想象加入现实的事件，将它们混为一谈。群体对主观和客观完全不予区分。他们把想象当中的画面当作现实，而这些画面与被观察到的事实之间，往往仅存一丝微弱的相似。”



“既然群体是由脾性迥异的个人组成，那么，群体对自己所目睹的任意一个事件所进行的歪曲，似乎应是多种多样，各不相同的。但实际情况并非如此。在传染的作用下，对事实的歪曲在每一个个体身上都表现出了相同的性质和方向。群体当中的某一个体对事实的第一次歪曲，是传染性暗示的关键点。圣乔治出现在耶路撒冷的墙上，这个画面肯定是先由在场的某个人率先看见，然后才被所有的十字军所看见。通过暗示和传染的作用，一个人所指示的奇迹，会立即被所有人接受。”



“误认通常是由女人和孩子，更确切地说，是由一些最易受影响的人所作出的。同时，这也让我们意识到这样的目击证人在法庭上的价值何在。尤其是孩子的证言，绝对不能当真。法官们喜欢老生常谈地说小孩子不会撒谎。但哪怕只要有一点基本的心理学素养，他们就该知道，恰恰相反，小孩子一直都在撒谎。或许只是无辜的谎言，但谎言始终是谎言。与其像很多时候所做的那样，以孩子的证词来决定对被告的判决，还不如用抛硬币的方式。”




“回到群体的观察力这个问题上，我们得出的结论是：集体观察通常都是错误的，它们最经常表现为，由一个个体的简单幻觉，通过传染作用，影响到群体中的其他人。我们可以引述无穷无尽的事实，来证明群体的证词不靠谱到怎样的地步。”



“逻辑学论著认为，为了证明一件事实的准确性，我们所能援引的最可靠的证据之一，就是大量证人的一致证词。然而我们的群体心理学知识告诉我们，在这个问题上，逻辑学的论文全部都该重写。最值得怀疑的事件，肯定就是那些被最多人所观察的事件。说一件事同时被上千目击者证实，这往往意味着所记述的事实与真相已经相去甚远。”




“从以上情况可以得出，历史书籍只能当作虚构作品来看待。它们是对观察有误的事件作出的不可靠记述，并伴随着事后的诠释。”



“对于一些在人类历史上发挥过重要作用的伟大人物，比如赫拉克利特、释迦牟尼、耶稣或者穆罕默德，我们对他们的生平，拥有过哪怕一句真实的记录吗？极可能一句都没有。不过，说实话，他们真实的生平对我们而言无关紧要。我们有兴趣了解的，是这些伟人被大众神话所创造出来的形象。打动群体心灵的，是传奇中的英雄，而绝非现实中的英雄本身。”



“在波旁王朝的统治时期，拿破仑成了一个拥护自由、不牟私利、田园牧歌般的人物、庶民的朋友，在诗人们的传颂中，他该会长久地留存在乡亲们的记忆中。三十年后，仁厚的英雄变成嗜血的暴君，在攫取了权力与自由后，他仅仅为了满足自己的野心，就让三百万人为他命丧黄泉。在如今，我们又见证着这个神话发生新的变化。再过几千年，当未来的学者面对这些矛盾百出的记载，也许他们甚至会怀疑这位英雄的存在，就像学者们有时也会怀疑释迦牟尼的存在一样。他们在他身上看到的只是太阳般的神话和一部赫拉克利特式的传奇历程。对于这种不确定性，他们也许能够轻松地接纳下来，因为，与今天的我们相比，他们更深谙群体心理学的知识，他们知道，若不靠神话，历史也就无从久存。”



“3.群体情感的夸张与简单化”



“无论群体所表现出来的情感是好是坏，它们都具有的双重特点就是：极为简单和极为夸张。在这一点上，就像在其他很多方面一样，群体中的个人类似于原始人。他无法对差异进行区分，只会囫囵地看待事物，而且不懂其中的演变。在群体当中，情感的夸张会因此而得到强化，因为展露出来的感情会通过暗示和传染非常快速地传播，而对这种感情的明显赞同则会大大增长它的力量。”



“在群体当中，愚蠢、无知和心怀嫉妒的人们摆脱了自身的卑微无能之感，取而代之的是一种粗暴、短暂但巨大的力量感。”



“群体身上的夸张倾向，常常会不幸地作用于一些恶劣的情感，这些属于原始人残留本能的返祖现象，在孤立且有责任感的个体身上会因害怕受罚而有所约束。而群体则会因此极其容易做出极端恶劣的行为。”



“群体夸大自身的情感，因此也只会被极端的情感所打动。想要抓住群体注意力的演说家，就必须措辞激烈。夸张、断言、重复，并且绝不试图以说理的方式证明任何事情，这些都是公共集会上的演说家们所惯用的论说手段。群体对他们的英雄人物也抱有同样的夸张情感。英雄人物的品质和他们表现出的美德必须始终被夸大。有人一针见血地指出，在戏剧中，观众会要求舞台上的英雄具备现实中不可能存在的勇气、道德和善良品质。”




“群体的夸大倾向只作用于情感，而绝对不作用于智力。我已经表明过，只要个体处于群体当中，他的智力水平就会立即大幅下降。这在塔尔德先生关于群体犯罪的研究中也证实过。”




“4.群体的偏执、专横和保守”



“群体只知道简单而极端的情感；提供给他们的意见、想法或者信仰，他们要么照单全收，要么全盘拒绝，不是视之为绝对真理，就是当作绝对谬论。于是，群体的信仰总是在暗示作用下被决定，而不是经由理性思考孕育而成。众所周知，宗教信仰是多么的偏执，它们对人们的思想产生的是怎样专制的统治。”



“专横和无知是一切类型的群体的共性，但其表现出来的程度千差万别；这时候，种族——这一决定人类所有情感和所有思想的基本概念，又会显现出来。尤其是在拉丁裔群体中，专横和无知达到了很严重的地步。它们是如此极端，以至于彻底破坏盎格鲁—撒克逊人身上强烈的个人主义独立精神。拉丁群体只关心其所属宗派的集体独立性，这种独立性的特征就是：急迫且粗暴地要求所有异见分子都来顺从他们的信仰。在拉丁民族中，自宗教法庭以来，所有时期的雅各宾派，都未能建立对自由的另一种理解。”



“对于群体而言，专横和无知都是非常明确的情感，是一种他们很轻易产生也很容易接受的情感，一旦受到唆使，他们就会将其表现出来。群体对强权俯首称臣，却丝毫不为仁义善良所打动，仁慈对于他们而言只意味着软弱。他们从来不顺应温和仁厚的主子，而是俯首于严厉压榨他们的暴君。对这样的暴君，他们总是为其立起高高的塑像。如果说，他们敢主动将被推翻的专制君主踩在脚底，那也是因为君主失去了权势，成为了他们毫不忌惮、可以尽情藐视的弱者中的一员。深得群体喜欢的英雄类型，永远是恺撒这样的形象。他的权杖吸引着他们，他的权威震慑着他们，他的利剑令他们畏惧。”

 Books. 

“对于软弱的政权，群体随时都准备着造反，而面对强权，他们则卑躬屈膝。如果当权者的势力起伏不定，那么，受到极端情感所控制的群体，就会在无法无天和婢膝奴颜之间交替反复。”



“不过，如果把群体的革命本能看作主导，那么，对群体心理的认知就有误了。让我们产生这种错觉的，只不过是群体的暴力倾向。他们的反叛和破坏行为的爆发，总是非常短暂。群体深受无意识的支配，因此也特别屈从于千百年来世袭制度的影响，所以，他们无可避免地因循守旧。”



“若对他们放任自流，他们很快就会厌倦混乱，本能地转变为奴才。当波拿巴剥夺了一切自由，对所有人痛施铁腕之时，向他发出热烈欢呼的，正是那些最桀骜不驯的雅各宾派。”



“事实上，他们的保守本性就像所有的原始人一样顽固”



“他们对传统的盲目崇拜是毋庸置疑的，他们对所有能够改变他们基本生存状态的新鲜事物，有着根深蒂固的无意识恐惧。如果在纺织机、蒸汽机和铁路被发明的时代，民主派就已经掌握了他们今日所拥有的权力，那么，那些发明是不可能被实现，或者说，是要付出不断的革命与杀戮的代价才有可能实现的。对于文明的进步而言，应该庆幸科学和工业的伟大发现都在群体力量尚未萌芽之时业已完成。”



“5.群体的道德”



“如果我们将“道德”一词理解为坚定地尊重某些社会习俗，持久地压抑自私的冲动，那么很明显，群体太易冲动、太易变化，因此不可能是道德的。但如果我们把某些短暂出现的品质，诸如忘我、奉献、不计私利、自我牺牲、追求公正等，都算入“道德”的概念中，我们反倒可以说，群体有时候是有着非常高的道德境界的。

少数研究过群体的心理学家们，都只是从犯罪行为的角度来观察他们；而且，考虑到这些行为的频繁程度，他们认为群体的道德水平十分低下。”



“情况常常就是如此，但为什么会这样？简单地说，因为原始时代残留下来的野蛮破坏力，是沉睡在我们每个人身上的本性。在每个孤立个体的生活中，满足这样的本性对他而言是危险的，然而一旦他并入了不负责任的群体当中，知道肯定不会受到惩罚，他就会彻底地放纵这种本性。由于不能总将这种破坏性本能发泄在自己的同胞身上，于是我们便对准了动物。正是源于这一点，群体对于狩猎和残暴行为有着普遍的热情。群体慢慢地折磨一个没有反抗能力的牺牲品，显示出的是一种懦弱的残忍；在哲学家看来，这种残忍，与十几个聚集在一起的猎人饶有兴致地围观他们的猎犬追逐并撕咬一只可怜的鹿时所表现出的残忍，有着同源的相似。”



“如果说，群体可以杀人放火、无恶不作，那么，他们也同样可以牺牲、奉献、大公无私，其行为的崇高甚至远远超过孤立的个体之所为。尤其是在身处群体的个人身上，往往能够唤起光荣、名誉、宗教与祖国的情感，使之奉献出自己的生命。像十字军远征和1793年志愿者那样的事例，在历史上比比皆是。唯有集体能够表现出伟大的无私与奉献。

多少群体为了他们一知半解的信仰、理想和只字片语慷慨赴死。罢工的人群往往更多地是为了服从一句指令，而非为了增加一点微薄薪水以满足自己。在群体当中，个人的利益极少会成为强大的动因，相反，在孤立的个体身上，它几乎是唯一的动机。当然，也并不是利益在引导群体投入那么多的战争，这些战争往往是他们的智识所无法理解的，但他们却轻易地在其中遭受屠戮，就像云雀被猎人所摆弄的镜子迷惑，丢掉性命。”



“即使是那些十恶不赦的坏蛋，也唯有在置身群体之时，会短暂表现出对道德规范的严格遵守，这样的事例时有发生。”



“在1848年大革命期间，蠢动叫嚣着攻陷了杜勒利宫的穷苦民众，也并没有染指任何一件光鲜的物品，而事实上哪怕随便一件，都可以换得多日的口粮。”



“虽然说群体常常放任自己低劣的本性，但他们也不时会成为崇高道德行为的典范。如果说，无私、顺从、全身心地投入某个虚幻或切实的理想，这些品质可以算作美德的话，那么我们可以说，群体对这些美德的拥有程度，是最智慧的哲学家也无法企及的。他们也许是在无意识中践行这些美德，但这又有什么关系。我们不应该太抱怨群体总是为无意识因素左右，总是不作思考。倘若他们时不时思考和追问他们的眼前利益，那么也许就没有任何文明会在我们这个星球上发展起来，人类也就不会拥有自己的历史了。”



