= “第三章　群体的观念、推理和想象力”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“1.群体的观念”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“我们在研究观念对民族演化的影响时曾经指出，每个文明都是从屈指可数的几个基本观念派生出来的，这些观念几乎不曾更新过。我们展示了这些观念如何在群体的心灵中建立起来，渗透的过程有多么艰难，而一旦渗透成功，它们又会具有怎样强大的力量。我们最终看到，那些重大的历史动荡，往往都是由这些基本观念的转变所引发的。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“我们可将这些观念分为两类。一类属于受一时环境的影响，偶然且短暂出现的观念：比如对某个人或某种教义的着迷。另一类属于基本观念，环境、遗传、舆论赋予其极强的稳定性：比如过去的宗教信仰，如今的民主观念和社会主义观念。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“虽然观念经历了改造，变得能够被群体所接受，但只有当它通过多种不同的手段（我们将另外研究）进入无意识领域并成为一种情感（这总是需要相当长的时间）时，它才能够发挥作用。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 


“切莫认为一种观念只因其正确就能够毫无疑问地产生效力。哪怕在有教养的头脑中也不可能。当我们看到，最清晰的证据对于绝大多数人的影响力却是多么微不足道，就能够很快明白这一点了。一件事实倘若明显而确凿，那么一个受过教育的人是会认可它，然而这个刚刚被说服的人很快就会被他的无意识带回到最初的想法里去。我们会看到，不出几天，他又会重新操起那些老论调，一字不改。事实上，他受到的是先前观念的影响，这些观念已经成为了情感；而正是它们，对我们言行举止的深沉动机发挥着作用。这对于群体也不例外。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 


“当一种观念终于通过各种不同的方式进入了群体的头脑后，它就具有了不可抵挡的力量，从而产生一系列不可小觑的效应。引发了法国大革命的那些哲学观念，花了近一个世纪的时间才生根于群体的心中。我们看到，它们一旦建立之后，产生的力量是多么势不可挡。整个民族为了获得社会平等，为了实现抽象的权利和理想中的自由所奋起的抗争，撼动了所有王室，深刻地震荡了西方世界。二十年间各国相互踩踏，欧洲经历了连成吉思汗和帖木儿都要心惊的大屠杀。一种观念所触发的后果能够达到这样的程度，在这个世界上可谓前所未见。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“让观念在群体的头脑里扎根，需要相当长的时间，而要去除它们，所需的时间也不会短。而且群体在观念上始终要落后于学者和哲学家们好几代。所有的政客都明白，我刚才提及的那些基本观念如今都混杂着错误，但由于这些观念的影响力仍然非常强大，所以他们不得不遵循着他们其实已经不再相信的原则来进行统治。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books.

“2.群体的理性”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“我们不能绝对地说，群体没有理性或不受推理的影响。但他们所采用的推论以及他们能接受的推论，从逻辑上看来，都处于非常低级的层次，要把它们纳入推理的范畴，甚为勉强。

和高级推理一样，群体低级的推理能力也是建立在关联基础之上的，但在群体所理解的关联观念之间，仅仅存在着表面上的相似性或连续性。它们的连接关系就像爱斯基摩人理解冰的方式：即通过经验知道冰是一种通体透明、放在嘴里会融化的物质，就认为同样是透明材质的玻璃，放到嘴里也应该会融化；又或者像野蛮人那样，以为吃下勇敢的敌人的心脏，就会得到他的胆量；或像工人，被一个老板剥削过，就立即认定天下所有的雇主都是剥削者。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“知道如何操纵群体的人，提供给群体的也就是这种层次的推理；唯有这样的推理方式才能够影响群体。一系列的逻辑推理对于群体而言是费解的，因此我们可以说，群体不会推理，或只会错误地推理，而且理性推论对群体无法产生影响。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“显而易见，群体在推理上的无能，也造成了其批判精神的缺失，也就是说，无法辨别真伪，无法对任何事物有清晰的判断。群体所接受的判断，只会是强加给他们的判断，而从不是经过探讨后得出的判断。从这点上看，很少有人能够超越群体的思维。有些见解之所以能轻而易举地得到普遍赞同，往往就是因为绝大多数人都没有能力根据自己的推理来形成独立的见解。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 


“3.群体的想象力”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“推理能力在群体身上完全不起作用，而群体所表现出的想象力则异常强大、活跃，且极其容易被触动。由一个人、一件事或一次意外在他们脑中所激发的形象，栩栩如生。群体仿佛一个处在睡眠状态的人，理性被暂时悬置，任由头脑中涌现层出不穷的形象，但一旦要付诸思考，这些形象又立刻消失不见。群体既没有思考能力也没有推理能力，于是不知道什么叫作不可能：不过，那些最不可能的事物，往往也就是最打动人的。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“当我们分析一种文明的时候，我们会发现，事实上，奇迹与传说才是其真正的支柱。在历史上，表象总是比真相扮演了更为重要的角色。非真实总是比真实更占据主导地位。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“征服者的权力和国家的威力，就建立在大众的想象力之上。要想引领群体，尤其要在这种想象力上下功夫。所有重大的历史事件，佛教、基督教、伊斯兰教的创立，宗教改革，法国大革命，以及当今世界社会主义的来势汹汹，都是因为群体想象力被强烈激发后，所产生的或直接或深远的后果。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“所有重大的历史事件，佛教、基督教、伊斯兰教的创立，宗教改革，法国大革命，以及当今世界社会主义的来势汹汹，都是因为群体想象力被强烈激发后，所产生的或直接或深远的后果。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“拿破仑对国会说：“我通过当天主教徒，结束了旺代战争；通过当穆斯林教徒，在埃及站稳脚跟；通过当一个拥护教皇无上权力的人，我赢得了意大利神父们的支持。如果我要去统治一个犹太国家，我甚至会重新建起所罗门神庙。”也许，自亚历山大和恺撒以来，没有哪个伟人能比他更了解应该怎样影响群体的想象力。他始终不变的第一要务，就是去激发它。在胜利时，在演讲时，在所有的言行举止中，他都不忘这一点。在垂死的病榻上，他也仍对此念念不忘。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“如何激发群体的想象力呢？我们马上就会看到。目前只需说明的是，方法从来都不是施力于智力或理性，即通过论证来实现。安东尼[19]成功地号召民众去对抗杀害恺撒的凶手，不是通过精妙的修辞演说，而是把恺撒的遗言读给他们听，把恺撒的尸体指给他们看。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

“并不是事件本身会刺激群体的想象力，而是它们发生与呈现的方式。必须通过浓缩加工（如果我可以这样说的话）使它们形成浓烈的形象，占据并控制群体的大脑。谁了解激发群体想象力的艺术，谁就掌握了统治群体的艺术。”

Excerpt From: 古斯塔夫·勒庞. “乌合之众：大众心理研究（法语直译未删减版，独家收录《论自愿为奴》） (译林人文精选).” Apple Books. 

