= “第二章　群体意见的直接因素”

 

“在研究群体的想象力时我们发现，它尤其容易被形象所影响。这些形象并非随时都在，但是可以通过合理地运用词语和套话来激活。”

 

“词语的力量与它们所唤起的形象相关联，但完全独立于其实际含义本身。含义最不确定的词语，往往拥有最强大的影响力。举例如下：民主、社会主义、平等、自由，诸如此类的字眼，它们的含义如此模糊，多少鸿篇巨著都无法将其说清楚。然而，它们短短的音节足以产生巨大的力量，仿佛拥有解决所有问题的魔法。潜意识中各种各样的憧憬，和实现它们的期待，全都集中在这几个词语当中了。”

 

“词语的意义始终是变幻的、暂时的，它们随着时代，随着民族的不同而发生改变。所以，当我们想通过词语去影响群体，我们必须知道的是这些词语在当下对于群体的意义，而不是它们曾经的意义或对于其他心理状态下的个体才可能具有的意义。”

 

“明智的托克维尔早在很久以前就指出，执政政府和帝国的工作其实就是用新的名称把绝大多数过去的制度重新包装一遍，也就是将那些会让群众联想到不利形象的词语替换为另一些能够防止产生类似联想的新词。地租改名为土地税，盐赋改名为盐税，徭役改名为间接税，行会和商号所须缴纳的税款则被称为执照税，等等。”

 

“在拉丁民族中，“民主”这个词意味着在国家所代表的集体面前抹除个人的意志和自主权。国家日甚一日地支配一切，集权、垄断并制造一切。无论是激进党、社会党还是保皇党，所有的党派都无一例外地要时时求助于国家。而在盎格鲁—撒克逊地区，尤其是在美国，同样的“民主”一词，则反过来意味着个人意志的强有力发展，与国家意志的尽可能退让。除了警察、军队和外交之外，人们不受国家的任何支配，包括教育也不例外。因此，同一个词，在一个民族里指的是对个人意志和自主权的抹杀，以及国家的优越，而在另一个民族里则意味着这种个人意志、自主权的极致发展，以及国家意志的彻底退让，也就是说，这个词包含着截然相反的意义。”




“经验几乎是唯一能够让真理在群体心中落地生根，让过于危险的幻象灰飞烟灭的有效手段。但是，必须让经验能够在一个非常大的范围内实现，并且循环反复。一代人的经验往往对下一代人没有用处；这就是为什么一些被援引来作为论据的历史事实起不到什么作用。它们唯一的用途就是证明，经验必须被一代又一代重复，才有可能产生某些影响力，才得以动摇到深深根植于群体头脑中的某一个错误观念。”



“民族的演化过程中最主要的因素从来不是真理，而是谬误。如果说社会主义在今天能够如此强大，那是因为它是唯一还存活着的幻觉。尽管有那么多科学的论证，但它依然在不停壮大中。它最核心的力量在于，它的捍卫者们完全无视现实，于是可以大胆地向人类承诺幸福。如今，这种社会主义幻想盛行在历史的废墟之上，而未来是属于它的。群众从未渴求过真理。面对那些不令人愉快的事实，他们宁可转过身去，将谬误奉为圣典，只要这谬误能够引诱他们。谁知道如何带给他们幻觉，谁就能轻易地成为他们的主人；谁试图令他们幻灭，谁就成为他们的牺牲品。

”




“而至少要用二十年灾难性的试验，人们才会认识到，贸易保护主义将会毁掉那些接受了它的民族。这样的例子，不胜枚举。”

 

“我们已经证明，群体是不受推理影响的，他们只能理解那些拼凑而成的观点。因此，懂得如何影响群体的演说家，总是利用群体的情感而非理性。”

 

“一个只遵循自己思路而不考虑听众思路的演说家，他的影响力会是零。”

 

“人的理性恐怕从未能够促使人类走上文明之路，反而是幻觉的热烈与大胆成就了它。我们受无意识力量的支配，而幻觉作为这种力量的产物，无疑是必不可少的。”

 

“我们必须研究一个民族进化的总体进程，而不是进化过程中时不时冒出的孤立事件，才有可能对这种力量产生一点点的认识。如果我们只考虑孤立的事件，历史就仿佛是由一个个不可能的偶然所支配。”

 

“因此，还是让我们把理性留给哲学家们，而不要在对人的统治中过于坚持理性的介入。并不是因为理性的存在，或者更应该说，尽管存在着理性，人类还是产生了诸如尊严、忘我、宗教信仰、对祖国与荣耀的热爱等等情感，而它们才是迄今为止所有文明的伟大动力。”

 


