= “第七章　用心理暗示打开心灵的潜能”

“No.1　暗示可以造成“弄假成真”的错觉，这种错觉能够帮助人们实现看似不可能达成的愿望。

No.2　你有一项高贵的、与生俱来的权利，如果不善加利用，这项权利就不为人知。这种权利就在我们的心里，相信或不信，要或不要，都由你决定。

No.3　暗示是在意识与潜意识之间搭起一座桥梁，可以帮助两者沟通和达成亲密的合作关系。

No.4　在暗示力的撬动下，我们内心的“潜能矿藏”可以帮助人们解决一切难题。

No.5　“我能”是一定能够实现的一种存在，也是每个人都应该挂在嘴边上的话语。”

“自我暗示就是自动暗示，它是人的心理活动中的意识思想的发生部分与潜意识的行动部分之间的沟通媒介。它是一种启示、提醒和指令，它会告诉你注意什么、追求什么、致力于什么和怎样行动，因而它能支配影响你的行为。”

 

 
“暗示具备创造性特质。

这就说明，暗示本身是具有创造性的，它可以让人的感官产生一些相对应的错觉，并因此刺激生理器官，得到相关的满足。

对于这一种现象，舒勒的解释是：“在人们的人格构成当中，都存在种种缺陷和不足。而这些缺点正好就给外来的正面影响预留了一部分弥补的空间。从另一方面来说，人们在自己的潜意识当中也会不自觉地意识到自己的缺点和不足，所以他们很容易就会接受那些来自自己信任者、崇拜对象的暗示和引导，最后对自己的人格进行补充和完善。”

 

“哪些人容易受到暗示的影响呢？舒勒认为，依赖性强，缺乏主见的人容易在暗示的作用力下偏离自己原来的轨道。因为这些人的神经相对脆弱，对于事物缺乏坚定的观点，因此个人信念摇摆不定，容易受到他人的影响。在相同环境下，女性更容易受到暗示的影响，因为从整体上来讲，女性对于外界的依赖性要普遍强于男性，这种稍显被动的特质让她们在暗示的敏感程度上领先于男性。”

 

“自我暗示其实就是一种自我控制，通过它，个人可以根据意愿在潜意识中，种下创造性的意念；也可能由于疏忽漠视，而任由破坏性意念在这片心灵沃土中生长。”

“你常告诉自己“我要拥有健康的身体”，潜意识就会将你的愿望实现。和你的潜意识反复、积极地对话是很重要的，因为潜意识就是梦想的启动器，你怎么说，它就会怎么进行。相信你一定常听到以下的对话：“我不能喝咖啡，它会让我睡不着觉”、“不能吃西瓜，会拉肚子”“不能坐飞机，会想吐”，等等。事实上，这些并非身体的真实反应，而是你输入潜意识的程式，你的身体随潜意识左右，自然出现“你所想要的”反应。”

 

“首先，他让十个人穿过一间黑暗的房子，在他的引导下，这十个人都成功地穿了过去。然后，心理学家打开房内的一盏灯，在昏黄的灯光下，这些人看清了房子内的一切，都惊出一身冷汗。这间房子的地面是一个大水池，水池里有十几条大鳄鱼，水池上方搭着一座窄窄的小木桥，刚才他们就是从小木桥上走过去的。
心理学家问：“现在，你们当中还有谁愿意再次穿过这间房子呢？”没有人回答。
过了很久，有三个人站了出来，其中一个小心翼翼地过去，速度比第一次慢了许多倍；另一个颤巍巍地走上小木桥，走到一半时，竟趴在小桥上爬了过去；第三个刚走几步就一下子趴下了，再也不敢向前移动半步。心理学家又打开房内的另外九盏灯，灯光把房间照得如同白昼，这时，人们看见小木桥下方装有一张安全网，由于网线颜色极浅，他们刚才根本没有看见，“你们谁愿意现在通过这座小桥呢？”心理学家问道。这时有五个人站了出来。“你们为何不愿意呢？”心理学家问剩下的两个人。“这张安全网牢固吗？”这两个人异口同声地反问道。”

“这些人之所以无法通过桥，失败的原因恐怕不是能力不济、智能低下，而是“作茧自缚”——在周围环境的威慑下产生了消极的心理暗示，以至慌了手脚、乱了方寸。”

“潜意识如同硬币的两面，哪一面朝上完全听命于暗示的传达。若是你想“破茧成蝶”，就要在潜意识中植入一个想要迫切实现的目标。”

“心理暗示是发挥自我潜意识的一个工具，也是让自己在脑海中形成理想画卷的美好开端，是让理想变为现实的重要前提因素。心理学大师弗洛伊德认为，潜意识的力量需要不断地进行心理暗示才能被激发出来，进而帮助你在脑海中形成美好的画面，并去实现它。”

“你所得到的财富，就是你价值的自我衡量；你所拥有的人生，就是脑海中对生活画面的勾勒。”

“诺曼·文森特·皮尔曾经说过这样一段话：“世界上最能驱动一个人的并不是由上而下的命令，而是由内而外的暗示。”

“是什么原因导致人们忽略自身的潜能呢？这可能有很多原因，比如懒惰、得过且过、安于现状等，但不明白心灵的构成是最根本所在。”

“意大利心理学家和精神学家阿沙鸠里在毕生研究西洋心理学时，提出了一张心灵地图，称之为“生命之蛋”，他把人的心灵分为七个不同领域。”

“第一个是“次级潜意识”，它会在本能上控制我们的行为及反应。表示在生命进行中所累积、压抑的心灵经验，譬如曾经因为车祸身心受创的人，即使身体康复了，仍无法立刻从车祸的恐惧中平静下来，因此当这个人处于车流间或类似车祸前的场景，他会自动开启恐惧的暗示的按钮；这也包括了内心深处的创伤，或某些压抑的信念，有许多慢性病和性格上的负面习性，其发生的原因都可在此发现，因此这部分必须用积极向上的能量去转化和提升。”

“第二个领域是“一般潜意识”，它的功能如同一个信息库，只是机械地接纳和记忆，让我们的意识能够进入其中搜寻它所要的资料。譬如某位太太擅长做比萨，但是当她在办公室跟主管开会讨论下年度工作计划时，她不需要同时在意识上记住做比萨所需要的知识，这些知识存在“一般潜意识”中，随时等待意识的召唤。”

“第三个领域是“表面意识”，也是最为我们熟悉的一部分，它总在持续变动中。我们可以观察到在持续不断变化的意念，它们可以仅是不断的流动，或成为进入行动的指令。在许多的暗示练习中，练习者初步必须安静这个“表面意识”，以便进入更深的意识去探索。”

“第四个领域是“个体的我”，也就是客观的自我，是意识、情感、行动的主人。每一个“个体的我”都有其形体的差异和心灵的独特特质，世界正是由不同的个体组成的。”

“第五个领域是“集体潜意识”，它是人格结构最底层的无意识，包括祖先在内的世世代代的活动方式和经验库存在人脑中的遗传痕迹。集体无意识和个人无意识的区别在于：它不是被遗忘的部分，而是我们一直都意识不到。荣格曾用岛打了个比方，露出水面的部分是人能感知到的意识；由于潮来潮去而显露出来的水面下的部分，就是个人无意识；而岛的最底层是作为基地的海床，就是我们的集体潜意识。我们并非完全与他人隔离，虽然每个个体有他自己的身体，有他自己的思想和情感，但是在群体之中，所有的人皆以心电感应的方式交流着彼此的生物磁场，因此一种共同的潜意识会存在相似文化、历史、地理或社会环境的族群中，这个族群的生活会共同受到这个集体潜意识的影响。”

“第六个领域是“高级潜意识”，从任何形式所呈现出来的灵感、启发皆从这个领域而来。不论在艺术、科学等不同的范畴里，来自高级潜意识的灵感会以一种迅疾的方式传递讯息给我们，它就像我们心中的一个小宇宙，能在我们肠枯思竭、百思不得其解时，出其不意地闪出一道金光，而使某个问题得以神奇地化解。”

 

“第七个领域是“灵性的大我”，这个大我即是宇宙智慧和力量的本身，是精神最高的升华，通过它我们可以和宇宙对话。”

“希望增强自信时：我才华很出众！我精力很充沛！我很能干！我很有主见！我很帅！我很美！我感觉很好！我的心情很好，没有什么事能难倒我！我记忆力很好，想象力很丰富，富有创造性！”

 

“希望改善人际关系时：我待人很诚恳，一定能收到好的回报！我很真诚，别人不会误会！我很坦荡，能够宽容别人！我很大方，别人喜欢和我交朋友！我很谦虚！我很诚信，言出必行！我很友善，这已经得到了证明！”

 

“希望高效工作时：我时间观念很强，对时间的利用很有效率！我很勤快，办事效率高！我很热爱自己的工作，我很负责，一定要保质保量！我很专注，很少受到干扰！”

“当你遇到难题时：我能找到解决问题的办法！我很自信，一定能办好这件事！我很坚强，失败不过是个小插曲！”

“希望自己健康时：我很喜欢运动，身体一天比一天强壮！我精神很愉快，心情舒畅，生活幸福，身体一直从中受益！我睡眠很好，每天精神焕发！”

“潜意识也是如此，如果你能够给它起一个它喜欢的名字，那么你就能触动它，获得它的认可与好感。”

“法国著名的哲学家西奥多·儒佛瓦说：“那些不相信潜意识的人，潜意识自然也是不会帮助他解决问题和困难的。”所以，相信潜意识是与潜意识达成良好沟通的开始和基础。如果你不相信潜意识，那么你与潜意识之间就会产生很深的隔阂，自然也就很难穿越这道门，而与之沟通就更谈不上了，这样一来，你内在的潜能就不能被挖掘出来。”

 

“与潜意识沟通的第一步就是使它平静下来。”

“最容易的方法是做深呼吸，在呼气时把注意力放在双肩上。同时做这两件事（呼气时把注意力放在肩膀），能改变自主神经系统的工作，抑制交感神经而活跃副交感神经系统。简单地说，就是开始放松。深呼吸三次后，肩膀的放松感觉会漫延到身体更多的部分。”

“潜意识天生内向，所以它不会很轻易地就向你敞开心扉，而且有时候它还会欺骗你，给你一些假象。向它发问是我们与潜意识进行沟通的首要方法。通俗地来讲，这可以说是在心理上进行的一种“博弈”。

向潜意识发问的时候，要保持开放的心态和中立的态度，不能提前预设你的立场，不能携带强烈的偏好。”

“在清晨或者临睡前向潜意识发问，就像从没提问过一样。”

“你的潜意识一直在寻找解决方案，但并不是所有问题马上就能解决的，有时需要一段时间，因此不要灰心，要学会耐心等待。这样你的潜意识才有足够的时间去实现你的愿望，满足你的要求。”

“我们要对潜意识抱很大的希望和意念，只有这样我们才能成功。”

“你的意识是启动器，你的潜意识是马达，你得首先启动这部马达，它才能工作。你的意识又如同发电机，用来唤醒潜意识的能量。”

“在向深层的潜意识传达想法时，首先要身体放松，让注意力减小，让心情平静下来。平静的心态可以排除杂念和错误想法的干扰。在平静的状态下，不要做什么努力，潜意识就会接收东西，然后开始想象你的愿望是什么，例如，你希望买幢新房子。”

“在向深层的潜意识传达想法时，首先要身体放松，让注意力减小，让心情平静下来。平静的心态可以排除杂念和错误想法的干扰。”

 

“切记，你在寻找的也在寻找你。”

 

“你的潜意识开始行动的时候就说明你已经成功了一半了，而不断地进行心理暗示和将坚定的信念引入心里则更加有助于你的潜意识的增强。如果能让你的潜能时刻受到潜意识的召唤，你脑中的那些美好画面很快就会变成现实。”

 

“一个人成功与否就看他能否突破自我，找到潜在的能量！”这是著名成功学家拿破仑·希尔的一句话。”

“当一个人的内心只想着某一种事情的时候，就会很难突破内心思维方式中的这面“墙”，很难抓住潜能量带来的力量，因此也就不可能取得较大的成功。这就好比思维的通道，有些人的思维一直沿着顺通的水管往前进，丝毫不会注意到身边的其他出口和方向，而其他的方向和出口有些已经出现，并且频频提醒着人们，但是这些人就是不能发现这些出口，可这些出口的外面恰巧就是成功的自由天地。”

“很多人之所以会说“不可能”，是因为这些人都被内心思维方式中的那面“墙”限制住了。显然，成功的人是不会局限在某一个思维模式中的，他们会不断地进行自我暗示，寻求自我内心的潜在机会和能力，并牢牢抓住潜意识所带来的力量，从而走向成功。”

 