= “第四章　群体信仰所采取的宗教形式”

 

“我们已经指出，群体不进行推理，而是对观念进行全盘的接受或拒绝；他们受不了任何讨论、辩驳，而施加于他们身上的暗示作用则彻底地侵占了他们的理解力，并且有立刻转化为行动的倾向。我们说过，受到恰当暗示的群体会随时准备为了别人提供给他们的理想而慷慨赴死。我们还看到，他们只知道狂暴和极端的情感，所以在群体身上，好感立刻变为崇拜，而反感一旦产生就会转化为仇恨。”

 

“当一个人崇拜某个神灵，他还算不上有宗教虔诚，只有当他将所有思想的精力、所有意志的恭顺、所有幻想的狂热，统统奉献给某项事业或某个人，将其作为他全部思想与行动的目标和指南时，他才可谓是一个有宗教虔诚的人。”

 

“群体的信念具有盲目服从、粗暴偏执，以及要求狂热宣传等属于宗教情感的特点；因此可以说，他们的所有信仰都具有宗教的形式。群体所拥戴的英雄，在他们看来就是一个真正的神。”

 

“所有宗教或政治信仰的缔造者之所以能够将它们建立起来，都是因为他们能够激起群体狂热崇拜的情感，这种情感让人们在崇拜和服从中寻找到自己的幸福，并随时准备为自己的偶像赴汤蹈火。任何时代都是如此。菲斯泰尔·德·库朗热在其论述罗马高卢人的杰作中准确地指出，维持罗马帝国的根本不是武力，而是它所唤起的宗教崇拜感。他理性地写道：“在世界历史上，没有哪个受各民族憎恨的统治形式可以延续五个世纪之久……我们无法解释，区区三十个帝国军团，竟可以迫使上亿人民俯首帖耳。”他们之所以臣服，是因为帝国的皇帝是伟大罗马的化身，像神一样受到全体子民的一致崇拜。帝国之内，哪怕是最小的村镇，也设有叩拜皇帝的祭坛。“在那个时期，从帝国的一端到另一端，到处可见一种新的宗教在人群中兴起，那就是把皇帝本人当作神来崇拜。在基督教之前的许多年里，拥有六十座城邦的整个高卢地区，共同在里昂城附近建起纪念奥古斯都皇帝的神庙……神庙的祭司们由高卢城邦联合选出，是当地的首要人物……把这些都归因于恐惧和奴性是不可能的。这些民族不可能全都是奴性的民族，而且也不能如此保持三个世纪之久。崇拜君主的不是廷臣，而是罗马。不是单单只有罗马，还有高卢，还有西班牙，还有希腊和亚洲。”



“面对群体，要么当他们的上帝，要么就一无是处。”

 

“不要以为这是发生在过去时代的迷信行为，如今已被理性彻底扫除。在与理性永恒的斗争中，情感从未被打败过。”

 

“如果无神论有可能被群体所接受，那么它所表现出的偏执排他，与宗教情感其实完全无异，而且在这样的外衣下，它会迅速成为一种迷信崇拜。一个实证主义小团体的演变给我们提供了有趣的例证。深刻的陀思妥耶夫斯基给我们讲述的虚无主义者的故事，很快就发生在了实证主义者身上。有一天，受到理性的感召，这个小团体摧毁了一间小教堂里祭坛上所有的神像，熄灭了蜡烛，随即用毕希纳和摩莱肖特[20]等无神论哲学家的著作替代被摧毁的神像，然后又虔诚地点燃了蜡烛。宗教信仰的客体是改变了，但他们的宗教情感，真的有所变化吗？”



“对于一些社会现象的研究，应该更多地着眼于心理学的角度，而非自然主义的角度。我们的大历史学家泰纳只从自然主义的角度研究法国大革命，因此他往往看不到事件的真正源起。他充分地观察了事实，但由于缺乏对群体心理的研究，他有时候并不能够找到事件的成因。事件的血腥、混乱和残酷令他感到恐怖，他在这场宏大历史事件的主人公们身上，看到的只是一群癫狂野蛮、放纵自己原始本性的乌合之众。当我们认识到法国大革命不过是一种新的宗教信仰在群体当中的建立，那么，大革命中的暴力、屠杀、宣传的需要、向所有君王发出的战争宣言，这一切也就都得到了解释。”




“类似于我刚才提到的大动荡，只有在群体想要它们出现的情况下，它们才有可能发生。再专制的君主也不可能促成它们。当史学家告诉我们圣巴托洛缪惨案时君王的所作所为时，他们表现出的是与君王们一样的对群体心理的无知。像这样的事件，只能是出自群体的手笔。最专制的君王所能动用的绝对权力，也不过能够稍稍提前或推迟事件发生的时刻而已。”

 

“我们看到的始终不是君王的权力，而是群体的灵魂。”

 


