= “第五章　议会”

 

“议会制度是所有现代文明民族的理想。这种制度认为，许多人聚集在一起会比少数人更有能力对某一问题做出明智而自主的决定。这种观念从心理学上说是错误的，但却被人们广泛接受。”

 

“我们从议会中还是可以看到群体的普遍特征：想法简单、易受刺激、易受暗示、情感夸张、受领袖人物的主导影响等。但是，由于其特殊的构成，议会群体表现出某些不同的特点。我们将在下面指出。”

 

“意见的简单化是议会群体最重要的特征之一。”

 

“议会中的群体特别容易受到暗示；而且，就像所有的群体一样，暗示来自于拥有名望的领袖人物；但是，必须指出，暗示性在议会群体中有着非常明确的界限。

在地方利益或地区利益的所有问题上，议会中的每个成员都持有固定的、不可改变的观点，任何论证都无法使其动摇。即使有狄摩西尼的辩才，也无法改变一个众议员在贸易保护或酿酒业特权等问题上的投票，这类问题代表着有影响力的选民们的切身利益。这些选民早在投票期之前就发出的暗示，足以压倒一切其他暗示，维持意见的绝对固定性。”

 

“如果一个议会中的成员事先没有形成不可动摇的意见，领袖人物在多数的辩论中终究还是真正的主导。

这些领袖的必要性是显而易见的，因为在任何国家的议会中，都可以看到他们以团体头目的名义存在。他们是议会的真正统治者。群体中的人没了首领就不知所措。这就是为什么议会中的表决通常代表的只是少数人的意见。

领袖很少以论理来发挥影响，而更多是通过他们的名望。最好的证据就是，如果他们的名望忽然被时势所剥夺，他们就不再具有影响力了。”

 

“英国哲学家梅因[61]说：“我们时常从下议院的争论中看到，整个辩论不过就是暴烈的人们用无力的大话彼此交锋。这种一般的套话能够对纯粹的民主想象产生巨大的影响。”

 

“罗伯斯庇尔的演说，常常以其前后的矛盾性令人瞠目结舌；如果只看这些演说，人们完全无法理解，这个强大的独裁者是如何拥有这么巨大的影响力：

拉丁文化和教学辩论中的陈词滥调是用来服务那些既幼稚又平庸、在进攻和防守中只会像小学生一样说“那就上啊！”的人们。没有观点、没有技巧、没有俏皮话，狂言只会令人感到无聊。当人们走出沉闷乏味的演说厅，会迫不及待地像德穆兰[62]一样大叹一声：“唉！”

 

“一种与极端狭隘的头脑相结合的强大信念会赋予一个有名望的人什么样的力量，有时想想都令人恐惧。但必须满足这样的条件，一个人才可能漠视障碍、一往无前。群体本能地在这些精力旺盛、信仰坚定的人当中寻找自己的主子，他们总是需要这样的人物。”

 

“尽管在运作上有诸多困难，但议会仍是人类迄今为止所找到的最佳统治方式，尤其是最有可能摆脱个人独裁的统治方式。至少，对于哲学家、思想家、作家、艺术家和学者，总之一句话，对于所有构成文明金字塔顶端的人们而言，议会无疑是最理想的统治。

不过，事实上，它造成两种严重的危险：一是不可避免的财政浪费，二是对个人自由的逐步限制。

第一种危险是各种紧迫需求与选民群体缺乏远见的必然结果。如果一个议员提出一项符合民主理念的补偿举措，比如承诺所有工人的退休金补助，提高养路工人、小学教师待遇等等，而其他众议员由于害怕选民不满，不敢忽视其利益，于是也就不敢反对这项提案，尽管他们深知此举将大大加重财政预算的负担，并必然造成新税种的设立。他们在投票过程中是不可能犹豫的。增加开支的后果属于遥远的未来，对他们没有什么不利的影响，而如果投了反对票，造成的后果在他第二天面对选民的时候就会清清楚楚地展现出来了。”

 

“上面所提到的第二种危险，是因议会所造成的对自由不可避免的限制，表面上并不明显，但却千真万确。这是由大量法律造成的结果，而这些法律总是带有限制性。议会目光短浅，对其后果茫然无知，他们只认为自己有义务表决通过。”

 

“赫伯特·斯宾塞在很早以前的一本著作中就曾指出过，表面自由的增加必然伴随着真正自由的减少。在他最近的著作《个人与国家》中，他又再度谈到了这个问题。关于英国议会，他是这样说的：

这段时期以来，立法一直都走在我所指出过的路线上。快速膨胀的独裁政策不断地倾向于限制个人自由，这表现在两个方面：每年都有大量的法令被制定出来，对公民施加限制，过去完全自由的行为现在不能做了，而过去全凭个人意愿、可做可不做的事现在成为了必须完成的行为。同时，日益沉重的公共负担，尤其是地方上的公共负担，通过减少公民可以自由支配的利益份额，增加从他那里剥夺过来用于满足公共喜好的份额，进一步限制了他的自由。”

 

“各国的民众被这样一种幻象所蒙蔽，认为法律制定得越多，自由和平等就越能得到保障，于是他们每一天都在接受越发沉重的束缚。”

 

“在这些文明的诞生之初，一群来源不同的人，因移民、入侵或征服等偶然因素而聚集在一起。他们流着不同的血，说着不同的语言，信仰也各不相同，这些人之间唯一的共同纽带，就是某个首领半认可的法律。”

 

“当文明的强盛和复杂达到一定的程度之后，就停止了前进，而一旦止步不前，它就注定迅速衰落。它的老年时期来到了。”

 

“这个不可避免的时刻，总是以支撑种族精神的理想走向衰弱作为标志的。随着这一理想变得苍白无力，一切在它的激励下建立起来的宗教、政治或社会基础，都开始动摇。

随着理想的逐步消亡，种族也日益失去其团结、统一、强大的源泉。个人的个性和智力可以增长，但与此同时，种族的利己主义被个人利己主义的过度发展所取代，随之而来的是个性的弱化和行动力的减少。形成一个民族、联盟、集团的群体，最终变成一群没有凝聚力的个人，仅仅在某些时刻，因为传统和制度而人为地维系在一起。”

 


“这时，因个人利益和愿望而四分五裂、无法自我治理的人们，在最微不足道的行为上都需要被领导，于是国家开始发挥它铺天盖地的影响力。

随着古老理想的彻底丧失，种族最终也完全失去了自己的精神；它只不过是一群孤立的个人聚集在一起而已，这就又回到了最初开始的状态：一群乌合之众。它身上的特质短暂易变，既不可靠，也没有未来。文明失去了稳定性，只能随波逐流。平民为王，莽夫横行。这个文明也许看上去还是灿烂的，因为它那由悠久历史所赋予的华丽外表仍在，但事实上它的根基已被腐蚀，岌岌可危的大厦，在下一场风暴来临之时就将土崩瓦解。

在追求梦想的过程中，从野蛮走向文明，再随着梦想力量的失去，走向衰落和死亡，这就是一个民族的生命循环。”

 
