= “第二章　被称为犯罪群体的群体”

 

“群体犯罪的动机通常来自强烈的暗示，参与犯罪的个人在事后会坚信自己是在履行一项义务，这与平常的犯罪情况大不相同。”

 

“巴士底狱监狱长洛奈先生的遇害可以作为一个典型例子。当监狱被占领，狱长被疯狂的人群围住，拳打脚踢从四面八方向他袭来。人们建议把他吊死，砍下他的脑袋，或是将他拴到马尾巴上。在挣扎中，他无意踢到了其中一个参与者。于是有人建议，就由这个挨了一脚的人来割断狱长的喉咙，这个建议立刻得到了群体的响应。

此人是个无所事事的厨子，闲逛到巴士底狱只是想看看发生了什么事，他认为既然这是大家的意见，是爱国主义的行为，于是他相信杀死恶魔甚至可以获得一枚勋章。他用别人递过来的刀向那裸露的脖子捅去，但那把刀太钝了，砍不断，于是他从自己兜里掏出一把黑柄小刀（作为厨子，他对切肉很在行），顺利地完成了任务。”

“这里我们可以清楚地看到前面所提到的机制。服从于他人的教唆，这种教唆因为来自集体而不可抗拒，杀人者坚信自己做了件值得称道的事，而这种坚信是如此自然，因为他得到的是同胞的一致赞同。这样的一种行为在法律上可视为犯罪，但在心理上却不是犯罪。”

“被称为犯罪群体的群体，他们身上的普遍特质也正是我们在所有群体身上都会看到的：易受教唆、轻信盲从、变化不定、夸大或好或坏的感受、彰显某些道德。”

“所有这些特质，我们都会在一个群体身上看到，他在法国历史上留下过最为灾难的记忆：“九月惨案”群体。他与制造圣巴托罗缪惨案的群体十分相似。这里我将引用泰纳根据当时的回忆录所记述的细节。”

“屠杀者群体包含了大约三百人，完全是一个典型的异质性群体。除了极少数的职业无赖外，群体中大多是各行各业的小店主和手艺人：鞋匠、锁匠、理发匠、泥瓦匠、职员、中介等等。他们受到怂恿，就像前面提到的那个厨子一样，完全相信自己是在执行一项爱国使命。他们既当法官又当刽子手，但完全不认为自己是在犯罪。”

 

“深信自身使命的重要，他们开始建立审判台，并立即表现出群体的简单化思维和更简单化的正义感。考虑到受指控的人数众多，他们首先决定将贵族、神甫、官员、王宫侍仆，也就是所有那些在爱国者眼中从事有罪职业的个人，不加任何审理，一律判处死刑。对其他犯人，则根据其外表和声誉来做出判决。这样，群体最基本的良心得到了满足，然后他们就可以合法地进行屠杀，释放他们残忍的本能（我曾讨论过这种本能的起源），而集体总是能把它更彻底地发挥出来。”

 

“他们在同一时间表现出相反的情感，他们的同情心常常与他们的残忍同样极端。

“他们对巴黎的工人怀有膨胀而冲动的同情心。在阿巴耶，当这个群体中的一员得知囚犯们已经二十六个小时都没有喝上水后，差点就要杀了那个玩忽职守的狱卒，还是犯人们纷纷为其求情才得以活命。当一个犯人被宣告无罪（由临时法庭宣布），看守和刽子手，所有人都争相拥抱他，拼命地为他鼓掌欢呼。”随后他们又继续屠杀其他人。在大屠杀过程中，一种欢快的气氛从未消散。他们围着死尸唱歌跳舞，“专为女士”准备了长凳，以便愉悦观赏处死贵族的过程。他们还一直表现出独特的公正性。阿巴耶的一名刽子手曾抱怨说，座位靠后的女士们看不真切，现场只有少数人能够享受到痛打贵族的乐趣，为了公平观看，他们决定让这些牺牲品缓缓经过两排刽子手，刽子手们只使用刀背砍人，以便延长其受苦的时间。在福斯监狱，人们可以看到受害人全身赤裸，被凌迟长达半个小时之久，直到每个人都看够了，再当着众人的面将他开膛剖肚。

但刽子手们并不是毫无顾忌的，他们还是会表现出我们曾指出过的存在于群体身上的道德意识。他们拒绝占有受害人的钱财和珠宝，并将它们统统送到会议桌上。”

  

“在他们的所有行为中，到处可见群体头脑所特有的简单粗暴的推理方式。于是，在屠杀了一千二百到一千五百名国家敌人之后，有人提出，那些关着老乞丐、流浪汉、少年犯的监狱，其实是在养着没用的吃饭人，因此不如把他们全部解决掉，这个建议立刻就被采纳。此外，这些人中当然有一些人民的敌人，比如一个名叫德拉卢的妇女，她是一个投毒者的遗孀：“她肯定对坐牢充满愤怒；如果她能办到的话，她会一把火烧了巴黎；她肯定说过这话，她是这么说过的。也把她除掉算了。”结论很明显，所有人都被处死了，包括五十多名十二岁到十七岁的孩子，他们都有可能变成国家公敌，因此当然很有必要把他们也一并解决掉。”

 

“1871年巴黎公社的历史也为我们提供了类似的事例。随着群体势力的增长和政府权力的不断退让，我们当然还会看到很多这样的情形。”

 
