= “第四章　选民群体”

 

“选民群体，也就是被召集来选择官职担任者的集体，属于异质性群体，但由于他们的行为仅限于一件指向明确的事情：从不同的候选人中做出选择，因此我们可以在他们身上观察到前面所描述过的某些特征。

他们表现出的群体特征往往就是：缺乏推理能力、没有批判精神、易怒、盲从和头脑简单。我们还可以从他们所做的决定中看到群体领袖的影响，以及我们之前列举过的那些因素的作用：断言、重复、名望和传染。”

 

“候选人最首要的条件是享有名望。个人名望唯有财富能够取代。才能，甚至天才，都不是成功的必要因素。

候选人享有名望的必要性，即能够不经讨论就让人们接受自己，是至关重要的。选民——其中大多数来自工人和农民——很少选择自己的同行来代表他们，是因为这种出身的人对他们而言不具有任何名望。如果他们偶然选出了一个与他们同等的人，那往往是因为一些次要原因，比如为了对抗某个大人物、某个平日里选民不得不依赖的强势雇主，他们以此获得翻身做主的短暂幻觉。”

 

“但享有名望并不足以保证候选人取得成功。选民特别需要别人满足他们的贪婪和虚荣；必须对他们极尽讨好之能事，并毫不犹疑地许下天花乱坠的诺言。如果他们是工人，那就竭尽所能辱骂痛斥他们的雇主。而对于竞选对手，则要运用断言、重复和传染等方法竭力挤压他，让人们确信他是一个十足的无赖，累累恶行众人皆知。显然，寻找所谓证据是毫无用处的。如果对手不了解群体心理，他就会努力用各种论据为自己辩护，而不是仅以断言来驳斥断言；可这样一来，他就没有任何获胜的机会了。”

 

“持续的观察证明，选民从来不会费心去了解自己选出的人是否履行了之前的誓愿，尽管当时选举他正是以那个誓愿为前提的。”

 

“至于理性对选民头脑可能产生的影响，千万不要去读那些关于选民集会的报道，以免产生错觉。在这种集会上，人们言之凿凿，相互痛斥，有时甚至殴打起来，但从来就不进行论证。”

 

“在所有不具名的集会中，不管是什么集会，哪怕其成员全部由受过高等教育的人构成，会上的争论也是一样的景象。我已经指出过，身处群体的人们会降到同样低的智力水平，这样的证明比比皆是。”

 

“我们必须承认，文明是处于金字塔顶端的少数精英的作品，随着金字塔层的加宽，智力水平也随之递减，其基底就是这个民族的大众。一个民族的伟大，如要建立在以人数取胜的底层成员的投票上，是不可靠的。还有一件毋庸置疑的事是，群众的选票往往是相当危险的。它们已经让我们付出过好几次外敌入侵的代价；而随着社会主义学说的胜利，异想天开的人民主权论必将让我们付出更惨重的代价。”

 

“与群体的信仰作对，不亚于与飓风作对。普选的信条在如今拥有和过去的宗教信条一样的威力。演说家和作家们说起它时表现出的恭敬和奉承，连路易十四都不曾享有。因此，对待它必须像对待所有宗教信条一样。唯有时间能对它起作用。”

 

“托克维尔说得对：“在平等的时代，人们并不相信对方，因为他们彼此相似；但正是这种相似性使得他们几乎毫无节制地信任公众的判断；因为在他们看来，既然大家知识水平相当，那么真理没理由不是站在大多数人这一边的。”

 

“我们所有的经济学家都受过高等教育，大多数是大学教授或院士，然而，他们何曾对任何一个普遍性问题：贸易保护、复本位制等达成过一致意见？原因在于，他们的学识只不过比普遍的无知看上去好一点点。面对充满未知的社会问题，人们的无知并没有什么两样。”

 

“因此，如果只由学识渊博的人组成选民群体，他们的投票也不会比如今的选民好多少。他们还是受到自己的情感和党派意志的支配。这丝毫不会减轻我们如今所面临的困难，并且我们必定还会遭遇来自身份团体的专制压迫。”

 

“不管是受到限制还是普遍拥有，不管是在共和制还是君主制下，是在法国、比利时、希腊、葡萄牙还是西班牙行使，群体的选举权在哪里都是一样的，它所表达的，不过是一个种族无意识的向往和需要。在每个国家中，被选中的人的平均水平代表的就是这个种族的平均心智。从一代人到另一代人，这种水平几乎没有变化。”

 

“我们再次落到“种族”这一之前已多次遇到的基本概念上，以及由此引出的另一个观念：即制度和政府对民众的生活并不真正产生多大的影响。民众主要是受到其种族禀性的支配，也就是说，受到祖先遗传残余的支配，所谓种族禀性，就是这些残余的总和。种族与日常生活的枷锁，就是主宰我们命运的神秘主人。”

 


